app/recipes/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, DecimalField, TextAreaField
from wtforms.validators import ValidationError, DataRequired
from flask_wtf.file import FileField, FileAllowed

class RecipeForm(FlaskForm):
    # dish_name = StringField('Dish Name', validators=[DataRequired()])
    # dish_description = TextAreaField('Description', validators=[DataRequired()])
    # dish_ingredients = TextAreaField('Ingredients', validators=[DataRequired()])
    # dish_instructions = TextAreaField('Instructions', validators=[DataRequired()])
    # dish_image = FileField('Image', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    # submit = SubmitField('Create Recipe')

    # TESTING
    dish_name = StringField('Dish Name', validators=[DataRequired()])
    dish_description = TextAreaField('Description', validators=[DataRequired()])
    dish_ingredient_whole_measurements = SelectField(u'measurements', choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3')])
    dish_ingredient_fraction_measurements = SelectField(u'measurements', choices=[('', ''), ('1/2', '1/2'), ('1/4', '1/4'), ('1/8', '1/8')])
    dish_measurement_type = StringField('Type', validators=[DataRequired()])
    dish_ingredient_name = StringField('Ingredient', validators=[DataRequired()])
    dish_instructions = TextAreaField('Instructions', validators=[DataRequired()])
    dish_image = FileField('Image', validators=[FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Create Recipe')



    # def validate_product_name(self, product_name):
    #     product = Product.query.filter_by(product_name=product_name.data.title()).first()

    #     if product is not None:
    #         raise ValidationError('Given product already exists!.')

app/main/routes.py
from flask import render_template, flash, request, jsonify, make_response
from flask.helpers import url_for
import requests
from werkzeug.utils import redirect
from app import db 
from flask_login import current_user, login_required
from app.models import Product, ProductSchema
from app.utils import total_recipes, total_task
from datetime import date, datetime
from flask import Blueprint
from config import Config
from app.main.forms import SchedulerForm
import csv
from os.path import exists

main = Blueprint('main', __name__)

@main.route('/', methods=['GET', 'POST'])
@main.route('/index', methods=['GET', 'POST'])
def index():
    tday = date.today().strftime("%A, %m-%d-%Y")
    products = Product.query.order_by(Product.product_name).all()
    num_items = len(products)
    recipe_counts = total_recipes()
    activate_gen = 'false'
    task_counts = total_task()

    for product in products:
        if product.quantity <= product.min_quantity:
            activate_gen = 'true'
            break

    user = current_user

    product_schema = ProductSchema(many=True)
    output = product_schema.dump(products) 
    res = make_response(jsonify(output), 200)

    return render_template('index.html', title='MoVentory', products=products,
        tday=tday, num_items=num_items, res=res.get_json(), user=user,
        activate_gen=activate_gen, recipe_counts=recipe_counts,
        task_counts=task_counts)


@main.route('/quantity-entry', methods=['POST'])
def quantity_entry():
    req = request.get_json()
    product = Product.query.filter_by(product_name=req.get('prod_name').title()).first()
    product.quantity = req.get('qty_value')
    product_schema = ProductSchema()
    output = product_schema.dump(product)
    db.session.commit()
    res = make_response(jsonify(output), 200)

    return res


@main.route('/search-entry', methods=['POST'])
def search_entry():
    req = request.get_json()
    product = Product.query.filter_by(product_name=req.get('search').title()).first()
    product_schema = ProductSchema()
    output = product_schema.dump(product) 

    if product is not None: 
        res = make_response(jsonify(output), 200)
    else:
        res = make_response(jsonify({"Error": "Product not found"}), 500)

    return res


@main.route('/products', methods=['GET'])
def products():
    products = Product.query.all()
    product_schema = ProductSchema(many=True)
    output = product_schema.dump(products) 
    res = make_response(jsonify(output), 200)

    return res


@main.route('/index/gen-prod-lists', methods=['GET'])
@login_required
def gen_prod_lists():
    products = Product.query.all()
    # Uncomment lines below after testing
    shopping_list = {"sheet1": []}
    
    for product in products:
        if product.quantity <= product.min_quantity:
            shopping_list["sheet1"].append(
                {
                    "item": product.product_name,
                    "currentQuantity": product.quantity,
                    "boughtQuantity": 0,
                    "movintoryId": product.id
                })

    if len(shopping_list['sheet1']) != 0:
        # POST shopping list to google sheet using sheety API
        sheety_endpoint = Config.SHEETY_ENDPOINT
        sheety_headers = { "Authorization": f"Bearer {Config.MOVENTORY_SHEETY_TOKEN}" }
        
        for item in shopping_list['sheet1']:
            requests.post(sheety_endpoint, json={"sheet1":item}, headers=sheety_headers)        
    else:
        flash(f'You do not need to go shopping yet.', 'info mt-2')
        return redirect(url_for('main.index'))

    res = make_response(jsonify(shopping_list), 200)

    return render_template('generated_lists.html', res=res.get_json())


@main.route('/index/refresh-list', methods=['GET', 'POST'])
def refresh():
    token = Config.MOVENTORY_REFRESH_TOKEN
   
    if request.method == 'POST':
        request_token = request.headers.get('Authorization')
        if request_token == token:
            shopping_list = request.get_json()
            response_data = shopping_list['sheet1']

            for item in response_data:
                product = Product.query.get_or_404(item['movintoryId'])
                product.quantity = int(item['boughtQuantity']) + product.quantity
    
            db.session.commit()

            return "{'response': 'Okay'}"
        return "{'response': 'BAD AUTH'}"
    return "{'response': 'This page is for refreshing your shopping list up to date.'}"


@main.route('/<int:product_id>', methods=['GET', 'POST'])
def quantity(product_id):
    product = Product.query.get_or_404(product_id)
    product_schema = ProductSchema()
    output = product_schema.dump(product) 
    res = make_response(jsonify(output), 200)

    return res

@main.route('/index/schedule_reminder', methods=['GET', 'POST'])
def schedule_reminder():
    form = SchedulerForm()
    schedule_file = f"{Config.MOVENTORY_SCHEDULE_PATH}/schedule.csv"

    if request.method == 'POST':
        title = form.title.data.title()
        date = form.date.data
        message = form.message.data

        try:
            with open(schedule_file, 'r') as csv_file:
                csv_reader = csv.DictReader(csv_file)
        except FileNotFoundError as e:
            with open(schedule_file, 'w', newline='') as new_file:
                fieldnames = ['Subject', 'DueDate', 'Message']
                csv_writer = csv.DictWriter(new_file, fieldnames=fieldnames)
                csv_writer.writeheader()
                csv_writer.writerow({'Subject': title, 'DueDate': date, 'Message': message})
        else:
            with open(schedule_file, 'a') as append_csv_file:
                fieldnames = ['Subject', 'DueDate', 'Message']
                csv_writer = csv.DictWriter(append_csv_file, fieldnames=fieldnames)
                csv_writer.writerow({'Subject': title, 'DueDate': date, 'Message': message})

        flash(f'"{title}" has been scheduled!', 'success mt-2')
        return redirect(url_for('main.schedule_reminder'))

    return render_template('reminder.html', form=form)


@main.route('/index/scheduled-list', methods=['GET', 'POST'])
def scheduled_list():
    csv_file = f'{Config.MOVENTORY_SCHEDULE_PATH}/schedule.csv'
    scheduled_list_dict = {"Task": []}
    tday = datetime.now().timestamp()

    if exists(csv_file):
        with open(csv_file, 'r') as file:
            read_csv = csv.DictReader(file)
            for line in read_csv:
                scheduled_list_dict['Task'].append({
                    'Subject': line['Subject'],
                    'DueDate': datetime.fromisoformat(line['DueDate'])
                })

        scheduled_list_dict = sorted(scheduled_list_dict['Task'],
            key=lambda x: x['DueDate'])

    
    return render_template('scheduled_list.html',
        scheduled_list_dict=scheduled_list_dict,
        tday=tday, enumerate=enumerate)


@main.route('/about')
def about():
    user = current_user
    version = 'v2'
    creation_date = 'September 19, 2020'

    return render_template('about.html', title='About', version=version,
        creation_date=creation_date, user=user)

app/recipes/routes.py
from crypt import methods
import json
import re
from os import path, remove
from textwrap import indent
from flask import render_template, flash, abort, request, url_for
from flask.helpers import make_response
from werkzeug.utils import redirect
from werkzeug.wrappers import response
from app.recipes.forms import RecipeForm
from app.utils import save_image, build_dict, load_recipes, make_recipe_input, \
    dumps_recipes, write_to_json_file, load_posted_json
from flask_login import current_user, login_required
from flask import Blueprint
from config import Config


recipes = Blueprint('recipes', __name__)

@recipes.route('/recipes-page', methods=['GET'])
def recipes_page():
    return render_template('recipes.html', data=load_recipes())


@recipes.route('/recipes-page/edit/image', methods=['POST'])
@login_required
def edit_recipe_image():
    old_name = make_recipe_input['Image']
    if len(request.files) > 0:
        data=load_recipes()
        d_name = build_dict(data['Recipes'], key="Name")
        idx = int(d_name.get(make_recipe_input['Name'])['index'])
        image_file = save_image(request.files['imageFile'])
        make_recipe_input['Image'] = image_file
    else:
        image_file = 'default.jpg'
        make_recipe_input['Image'] = image_file

    image_path = path.join(f"{Config.MOVENTORY_RECIPE_IMAGE_PATH}/" + old_name)
    
    if old_name != 'default.jpg':
        remove(image_path)

    dumps_recipes(data=data, dict=make_recipe_input, index=idx, edit=True)
    return {"response": "Got File"}


@recipes.route('/recipes-page/edit/<dish_name>', methods=['GET', 'POST'])
@login_required
def edit_recipe_dish(dish_name):
    data=load_recipes()
    d_name = build_dict(data['Recipes'], key="Name")
    form = RecipeForm()
    idx = int(d_name.get(dish_name)['index'])
    response_data = d_name[dish_name]
    dish_img = f'images/{response_data["Image"]}'

    if request.method == 'POST': 
        if request.is_json:
            received_json = request.get_json()
            try:
                dish_name = received_json['New_Name']
            except KeyError:
                dish_name = received_json['Name']

            make_recipe_input['Name'] = dish_name
            make_recipe_input['Description'] = received_json['Description']
            make_recipe_input['Ingredients'] = received_json['Ingredients']
            make_recipe_input['Instructions'] = received_json['Instructions']
            make_recipe_input['Image'] = received_json['Image']

            dumps_recipes(data=data, dict=make_recipe_input, index=idx, edit=True)
            return make_response(f'{{"response": "{dish_name} has been updated."}}')

    return render_template('edit_recipe.html', form=form, name=dish_name,
        edit=True, response_data=response_data, dish_img=dish_img)


@recipes.route('/recipes-page/recipe-maker', methods=['GET', 'POST'])
def recipe_maker():
    form = RecipeForm()
    loaded_recipes = load_recipes()

    if request.method == 'POST':
        if request.is_json:
            received_json = request.get_json()
            write_to_json_file(obj=received_json)

            return {"response": received_json}
        else:
            data = load_posted_json()
            if len(request.files) > 0:
                image_file = save_image(request.files['imageFile'])
                data['Image'] = image_file
            else:
                write_to_json_file(obj=data)

            dumps_recipes(data=loaded_recipes, dict=data)

            return make_response(f'{{"response": "{data["Name"]} has been added."}}')

    return render_template('recipe_maker.html', form=form)


@recipes.route('/recipes-page/<dish_name>', methods=['GET'])
def recipe_dish(dish_name):
    data=load_recipes()

    # Get all dish names and check if given name is true
    dish_names = [item.get('Name') for item in data['Recipes']]

    # abort 404 if dish_name does not exist.
    if dish_name not in dish_names:
        return abort(404)

    d_name = build_dict(data['Recipes'], key="Name")
    dish_info = d_name.get(dish_name)
    dish_info_image = f"images/{dish_info['Image']}"

    return render_template('dish.html', data=data, dish_info=dish_info,
        dish_info_image=dish_info_image)

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, make_response
from app import db
from app.users.forms import LoginForm
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User, Feedback
from werkzeug.urls import url_parse
from flask import Blueprint

users = Blueprint('users', __name__)

@users.route('/feedback', methods=['GET', 'POST'])
def feedback():
    user = current_user
    feedbacks = Feedback.query.order_by(Feedback.timestamp.desc()).all()

    return render_template('feedback.html', title='Feedback', feedbacks=feedbacks, user=user)

@users.route('/login', methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Invalid username or password', 'danger mt-2')
            return redirect(url_for('users.login'))

        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('main.index')

        flash(f'Welcome {form.username.data.title()}!', 'success mt-2')
        return redirect(next_page)

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/about.html
{% extends "base.html" %}
{% block content %}
  <div class="container mt-4">
    <h2 class="text-center">About</h2>
    <div class="row">
      <div class="col-md-6 mx-auto text-muted text-center border p-2 small-table-text">
        <p>Something about this site.</p>
        <p>Version: {{ version }}</p>
        <p>{{ creation_date }}</p>
      </div>
    </div>
{% block search %}{% endblock search %}
{% endblock content %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% if title %}
      <title>{{ title }}</title>
    {% else %}
      <title>MoVentory</title>
    {% endif %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="{{url_for('static', filename='/css/bootstrap5/bootstrap.min.css')}}" rel="stylesheet" type="text/css">
    <link href="{{url_for('static', filename='/bootstrap_icons/bootstrap-icons.css')}}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='/css/style.min.css')}}">
    {% block css %}{% endblock css %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark-nav sticky-top border-bottom p-0 mb-1">
      <div class="container-fluid">
        <a class="navbar-brand fs-2 text-secondary" href="{{url_for('main.index')}}">MoVentory</a>
        {% block navigation %}{% endblock navigation %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mb-2 mb-lg-0 fw-bold ms-auto">
            <li class="nav-item me-4"><a class="nav-link" href="{{url_for('main.index')}}">Home</a></li>
            <li class="nav-item me-4"><a class="nav-link" href="{{url_for('recipes.recipes_page')}}">Recipes</a></li>
            {% if current_user.is_authenticated and current_user.id == 1 %}
              <li class="nav-item me-4"><a class="nav-link" href="{{url_for('managements.manager')}}">Manager</a></li>
              <li class="nav-item me-4"><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('users.logout')}}">Logout</a></li>
            {% elif current_user.is_anonymous %}
              <li class="nav-item me-4"><a class="nav-link" href="{{url_for('main.about')}}">About</a></li>
              <li class="nav-item"><a class="nav-link" href="{{url_for('users.login')}}">Login</a></li>
          </div>
            {% endif %}
          </ul>
          </div>
        </div>
      </div>
    </nav>
    
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-{{category}}">{{message}}</div>
        {% endfor %}
      {% endif %}
    {% endwith %}
  {% block content %}{% endblock content %}
{% block script %}{% endblock script %}
<script src="{{url_for('static', filename='/js/main.js')}}"></script>
<script src="{{url_for('static', filename='/js/bootstrap5/bootstrap.bundle.min.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
</body>
</html>

app/templates/create_post.html
{% extends "base.html" %}
{% block content %}

{% block search %}{% endblock search %}
    <!-- <div class="col-md-8 mt-2">
        <div class="row">
            <div class="col-md-12">
                <div class="p-2 border rounded-top bg-secondary text-white" id="title">My First Post</div>
                <div id="message" class="p-2 border border-top-0 bg-white">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quod amet rerum non natus, impedit consectetur maxime beatae? Culpa quod ipsam necessitatibus non illo eveniet maiores sed numquam dicta. Delectus, modi?</div>
            </div>
        </div>
    </div> -->


{% block script %}
{% endblock script %}
{% endblock content %}

app/templates/delete_recipe.html
{% extends "base.html" %}
{% block content %}
    <div class="container rounded mt-2">
        <!-- Alert -->
        <div class="alert alert-success d-none" role="alert"></div>
        <div class="col-12 col-lg-6 mx-auto">
            <h1 class="text-center">Delete Recipe</h1>
            <div class="row p-2" id="recipes-list">
                {% for dish in recipes['Recipes'] %}
                <div class="col-12 col-lg-4 mb-2">
                    <div class="card border-light">
                        <ul class="list-group list-group-flush text-center">
                            <button class="list-group-item btn btn-secondary text-dark text-decoration-none" data-bs-toggle="modal" data-bs-target="#deleteModal">{{ dish['Name'] }}</button>
                        </ul>
                    </div>
                </div>
                {% endfor %}
            </div>

            <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">Delete this recipe?</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button class="btn btn-danger" type="submit" id="deleteRecipeButton">Delete</button>
                        </div>
                    </div>
                </div>
            </div>            
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block script %}
<script>let recipes = {{ recipes|safe }};</script>
<script src="{{ url_for('static', filename='/js/delete_recipes.js') }}"></script>
{% endblock script %}

app/templates/product.html
{% extends "base.html" %}
{% block content %}
    <div class="container mt-2">
        <div class="row">
            <div class="col"></div>
            <div class="card col-12 col-lg-6 p-0">
                <!-- <img src="..." class="card-img-top" alt="..."> -->
                <div class="card-body">
                    <h3 class="card-title text-dark font-weight-bold mb-3">{{ product.product_name }}</h3>
                    <hr>
                    <dl class="row">
                        <dt class="col-sm-3">Type</dt>
                        <dd class="col-sm-9">{{ product.product_type }}</dd>
                        <dt class="col-sm-3">Package</dt>
                        <dd class="col-sm-9">{{ product.package_type }}</dd>
                        <dt class="col-sm-3">Quantity</dt>
                        <dd class="col-sm-9">{{ product.quantity }}</dd>
                        <dt class="col-sm-3">Price</dt>
                        <dd class="col-sm-9">{{ product.price }}</dd>
                    </dl>
                    <a class="btn btn-info btn mt-1 mr-1 mb-1 ml-0" href="{{ url_for('managements.update_product', product_id=product.id) }}">Update</a>
                    <button class="btn btn-danger btn m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                </div>
                <!--                 <div class="card-footer">
                    <small class="text-muted">Last updated 3 mins ago</small>
                </div> -->
            </div>
            <div class="col"></div>
        </div>
        <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Product?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <form action="{{ url_for('managements.delete_product', product_id=product.id) }}" method="POST">
                            <button class="btn btn-danger" type="submit">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          ...
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  
    {% endblock content %}

app/templates/recipes.html
{% extends "base.html" %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='/css/style_recipes.css') }}">
{% endblock css %}
{% block content %}
    <div class="container mt-4">
      <div class="row row-cols-lg-4 row-cols-sm-2 row-cols-md-3 row-cols-1 g-4">
        {% for recipe in data.Recipes %}
        <div class="col">
          <div class="card h-100">
            <div class="recipe-card-bg-img-container" style="background-image: url({{url_for('static', filename='images/' + recipe.Image)}});">
              <div class="recipe-card-bg-img-set-wh"></div>
            </div>
           
            <div class="card-body d-flex justify-content-between pb-0">
              <div>
                <a href="{{ url_for('recipes.recipe_dish', dish_name=recipe.Name) }}" class="text-decoration-none text-dark">
                  <h6 class="card-title">{{ recipe.Name }}</h6>
                </a>
              </div>
              <div>
                <a href="{{ url_for('recipes.edit_recipe_dish', dish_name=recipe.Name) }}">
                  <i class="bi bi-pencil-square fs-5 text-muted"></i>
                </a>
              </div>
            </div>
            <div class="p-3 pt-0">
              <p class="card-text small-info-text">{{ recipe.Description }}</p>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
{% endblock content %}

app/templates/reminder.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
    <div class="row mt-4">
      <div class="col-md-6 mx-auto">
        <h2>Schedule</h2>
        <p class="small-info-text">Set a date to remind you by email about something.</p>
      </div>
    </div>
    <form method="post", novalidate>
      <div class="row">
        <div class="col-md-6 mx-auto border p-2">
          <div class="mb-3">
              {{form.title.label(class="form-label px-2")}}
              {{form.title(class="form-control", placeholder="Change Filter")}}
          </div>
          <div class="mb-3">
              {{form.date.label(class="form-label px-2")}}
              <input type="date" class="form-control" name="date">
            </div>
          <div class="mb-3">
              {{form.message.label(class="form-label px-2")}}
              <p class="px-2 text-muted small-info-text">The message input will be the body of the email that will be sent to you.</p>
              {{form.message(class="form-control", rows="3")}}
          </div>
          <div class="mb-3">
            <button class="btn btn-primary" type="submit">Set Schedule</button>
          </div>
        </div>
      </div>
    </form>
    <div class="row mt-2 p-0">
      <div class="col-md-6 mx-auto border-top p-0">
        <a href="{{url_for('main.scheduled_list')}}" class="btn text-primary ps-2 small-table-text"><i class="bi bi-card-list fs-5 text-secondary"></i> See all scheduled list here</a>  
      </div>
    </div>
   </div>
{% block search %}{% endblock search %}
{% endblock content %}

app/templates/sortedByPkg.html
{% extends "index.html" %}
{% block sort %}
    {{ thd.thead(href1=url_for('index'), href3=url_for('sortedBy', sortBy='quantity')) }}
{% endblock sort %}

{% block paginate %}
    {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if products.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('sortedBy', sortBy='package', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('sortedBy', sortBy='package', page=page_num) }}">{{ page_num }}</a>
            {% endif %}  
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock paginate %}